### ISSUE TITLE
Use 3rd party query builder

### ISSUE THREAD

**Issue by stalniy** [B4nan/mikro-orm#56]
It would be awesome to be able to use custom QueryBuilder like https://knexjs.org/. It has a lot of cool features, migration support, seeding, etc.

**Comment by B4nan** [comment]
I was thinking about that some time ago. In the end you could use it just to generate the query and execute it via `driver.execute()` right now:

```
const query = knex.select('*').from('users')
  .where(knex.raw('id = ?', [1]))
  .toSQL();

const driver = orm.em.getDriver<MySqlDriver>();
const res = await driver.execute(query.sql, query.bindings);
```

But this way one would have to use real field/table names. Another option is to extend/reimplement the query builder. Not sure how the integration should work, WDYT? 

Btw I am planning to add support for migrations via https://github.com/sequelize/umzug some time in the future.

**Comment by stalniy** [comment]
I think there are 2 options:
* implement your SqlQueryBuilder based on knex
* add thin abstraction over QueryBuilder so any QueryBuilder library can be connected

If you integrate knex, you will get migrations and seeds for  free :) Also community of your lib potentially will grow because those who knows and uses knex will feel comfortable when using your ORM (I guess).

The good think about knex is that it abstracts query building very well. Sometimes you need to exec some crazy query (e.g., recursive query) but at the same you want to have a good level of portability between database vendors. And knex allows this. Not sure about implementation details but I like their interface :)

The example you showed with mapping is quite cool actually! Maybe if you could export this as some utility function or base method in Repository, so other can use this, it would be awesome.

**Comment by B4nan** [comment]
What I still do not understand fully is the way you would like the result to be let's say better for user. If I change the implementation of QueryBuilder, there will be pretty much zero difference for user, as its public API will remain the same. If the desired result is to use knex as a query builder instead of what currently sits inside ORM as `QueryBuilder` class, then my example above is the way to go. Sure I can wrap that code somewhere so its easier to use, I just need to understand what should be the result. 

So if the result should be easy way to use knex _instead_ of internal `QueryBuilder`, then it might be just the mapping code from above hidden under something like `EntityManager.runKnexQuery()` method (not very nice name, lol):

```
const query = knex.select('*').from('users').where(knex.raw('id = ?', [1]));
const entities = await orm.em.runKnexQuery(User, query); // root entity is needed
```

I could imagine `KnexQueryBuilder` class that would extend/wrap knex and be able to do this (as I definitely do not want to pollute EM API with this). It would have same API as knex with execute method that would handle the mapping. This thing could live inside the repository as part of `utils` folder. 

```
const qb = new KnexQueryBuilder(orm.em, User); // one would have to pass the root entity probably
qb.select('*').from('users').where(knex.raw('id = ?', [1])); // same API as knex
const entities = await qb.execute(query, { mapEntities: true });
// `mapEntities` flag is something I am planning to add anyway to ease the usage of QB, it will do the `orm.em.merge()` part automatically then
```

Also, how will I get migrations and seeding for free? One can always add knex to the project for such thing, it can live next to the ORM without any problem I believe, sure with the obstacle of having different field names than entity property names. Again, can you propose some way of how the API could look like?

**Comment by stalniy** [comment]
My initial intention to create this issue was the desire to use knex for advanced cases (recursive queries). Knex allows to do powerful things and keep queries at least semi-abstract relatively to database vendor.

I guess that it's enough to have `EntityRepository.map(userProps)` (I guess you call this  API to fulfill this issue requirement, so then it's possible to use knex at repository level:

```js
class UserRepository extends EntityRepository {
  async findById(id) {
     const results = await knex.select('*')
       .from('users') // here I can use for example `.from(this.tableName)` or something similar
       .where(knex.raw('id = ?', [id]));
     return results.map(user => this.map(user))
  }
}
```

But if you support such behavior, then I don't know whether it make sense to have own QueryBuilder abstraction. I don't know.

About migrations and field names, frankly speaking I don't think it's a big issue to use different names in migrations and in models (at least currently this is how I do in my app :)).

I don't think that it make sense to add additional level of ORM abstractions on top of migrations because then it will be hard to do low level configuration of the database

**Comment by B4nan** [comment]
It definitely makes sense to keep current `QueryBuilder`, as its pretty smart in terms of joining (see implicit joining here: https://b4nan.github.io/mikro-orm/query-builder/). It uses entity metadata under the hood. knex is just a 'native sql query builder', you have to instruct it about everything like what are join columns and pivot table names, etc. 

Will think about this later, having some deadlines now, but adding support to repositories probably makes the most sense. Currently there is only `this.em` and `this.entityName` but adding some helper method for table name is not a problem (in the end one can always get the entity metadata from static storage helper class as in my previous comments).

**Comment by B4nan** [comment]
FYI started to play with knex as a base layer for SQL drivers. Not really because of your concerns, but because of other features I would like to cover in near future - schema diffs and pooling mainly. Also I could easily get support for more SQL dialects to cover more databases. It might end up with some BC breaks (but save a lot of code), so v3 might be ahead of us :]

**Comment by B4nan** [comment]
I will close this one with #61, integrating knex will take more time and work, will create new issue for that once I am sure how to proceed. I was surprised that knex is not really 100% ready as few workarounds I did are not present there and had to be done via `knex.raw` (like cascading truncate in postgre). Also the `knex.raw` does not behave the same as executing on raw driver level, although they say so (e.g. in sqlite it does not return inserted id although the underlying driver does return it), but it works consistently when using `knex.insert()...` (which means I will need to rewrite the `QueryBuilder` to use `knex` under the hood). 

At this time I won't provide metadata at repository level, but you can access the global storage manually if you want to get the table name and property field names based on your entity metadata (`const meta = MetadataStorage.getMetadata(Book.name);`). You can create your own base repository with those helpers and register it in `MikroORM.init({ entityRepository: MyBaseRepository })` so all repositories will use it.
